### ISSUE TITLE
Feature proposal: surface svg aspect ratio

### ISSUE THREAD

**Issue by whereswaldon** [inkeliz/giosvg#1]
I could just be missing the obvious way to do it, but right now I can't figure out how to lay out an SVG icon without hard-coding its aspect ratio. If I just want to use the native aspect ratio of the icon, but centered within a square area, I can't seem to do it without distorting the icon. I see that the SVG's builtin viewport is available in [here](https://github.com/inkeliz/giosvg/blob/5eaaf2e77e84b2e975d4b1324729f745622c1263/internal/svgparser/svgparser.go#L34). What would you think about surfacing that in either the `Vector` or `Icon` type?

**Comment by inkeliz** [comment]
The main issue is that `giosvg.Vector` is one function, because that is shared with the generated SVG (for instance: https://github.com/inkeliz/giosvg/blob/master/example/school-bus.go). _I did that to avoid XML imports for WASM, and allocations during runtime. Since it's one function, the runtime and "compile-time SVG" can work with the same API._

I think it's possible to extend it to one interface, and then have one `Viewbox()`. However, in most cases the reason for Viewbox is to keep the aspect-ratio, so I think it can be also implemented somehow.

Changing:

```
type Vector func(ops *op.Ops, w, h float32)
```

To:

```
type Vector func(ops *op.Ops, maxW, maxH float32, minW, minH float32)
```

So, if you give `gtx.Constraints.Max.X == gtx.Constraints.Min.X` (and the same for Y) it will not do anything, it will not follow any aspect ratio. If the `Min.X = 0` and `Min.Y = 0` then it can resize the icon to use the maximum size available, but keeping the aspect-ratio (based on Viewbox). 

Example, if the icon is 10x10 (1:1), and you give: `Max.X = 50;  Max.Y = 20; Min.X = 0; Min.Y = 0;` then it will render one icon of 20x20, and the `layout.Dimensions` will return `20x20` too, so you can add some padding.  If you give `Min.X = 50`, it will return one icon of 50x20, breaking the aspect-ratio because of the `.Min` settings.

I think the Min/Max also follows the Gio pattern. If you want something at specific size, set `Max = Min`, otherwise, you are saying that the size is variable, in that case: keeping the aspect ratio.

**Comment by inkeliz** [comment]
Does it fixes the issue in your case? Please, re-open if it doesn't fix the issue.

Using #5 you can set `gtx.Constraints.Min = image.Point{}` to use aspect-ratio. You can use any other `Min` value as minimum size too, it will use the min value instead of the aspect-ratio.

```
layout.Center.Layout(gtx, func(gtx layout.Context) layout.Dimensions {
    gtx.Constraints.Min = image.Point{} // Keep aspect ratio.
    return your_icon.Layout(gtx)
})
```

You can see the example here: https://github.com/inkeliz/giosvg/pull/5/commits/9314721ebba76bfb9cd440c001b5744eaab91f1b#diff-1c171c5d51ba71728458fc771ff98395bcd3f59481e736c18e059372723acaabR46-R58

**Comment by whereswaldon** [comment]
Thanks @inkeliz, that does fix this problem.
